### ISSUE TITLE
是否有支持UDP计划

### ISSUE THREAD

**Issue by chobitsos** [honwen/luci-app-haproxy-tcp#2]
我看官方haproxy已经支持了UDP，看看是否能实现
![69269605-b3277780-0bd1-11ea-91ac-372eed7b6cf1](https://github.com/honwen/luci-app-haproxy-tcp/assets/18194327/74634245-f461-4d69-a522-91543c149c53)

**Comment by honwen** [comment]
seems openwrt's haproxy DOESN'T support udp

<img width="707" alt="image" src="https://github.com/honwen/luci-app-haproxy-tcp/assets/12322033/dc6d360a-e63c-4861-84af-3f052f8fbe11">
